version: "3.8"

services:
  projet_rh:
    build: .
    container_name: projet_rh_container
    volumes:
      - .:/app          # Pour dev, synchronisation code hôte ↔ container
      - ./db:/app/db    # Persistance base SQLite hors du container
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python run_project.py